name: Verification
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ‚öôÔ∏è Set up repository
        uses: actions/checkout@v2

      - name: ‚ùáÔ∏è Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x

      - name: üì¶ Install dependencies
        run: npm install

      - name: üíÖüèΩ Analysing code linter
        run: |
          npm run lint
          npm run prettier

      - name: üß™ Run Cypress Test
        uses: cypress-io/github-action@v5.0.0
        with:
          start: npm run dev
          browser: chrome
          record: false
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 300
        env:
          API_URL: ${{ secrets.API_URL }}
          DEV_EMAIL_ADDRESS: ${{ secrets.DEV_EMAIL_ADDRESS }}
          API_KEY: ${{ secrets.API_KEY }}
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          APP_ID: ${{ secrets.APP_ID }}
          MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}


      - name: üîç SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}